config/routes.rb
Rails.application.routes.draw do
  root 'home#gossip'
  get 'user/show', to: 'user#show'
  get 'home/gossip', to: 'home#gossip'
  get 'home/show_gossip', to: 'home#show_gossip'
  get 'welcome/:first_name', to: 'welcome#first_name'
  get '/team', to: 'static#team'
  get '/contact', to: 'static#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user, required: false
    belongs_to :tag_gossip, required: false
    has_many :tags, through: :tag_gossips
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender, class_name: "User", required: false
    belongs_to :recipient, class_name: "User", required: false
end

app/models/tag.rb
class Tag < ApplicationRecord
    belongs_to :tag_gossips, required: false
    has_many :gossips, through: :tag_gossips
end

app/models/tag_gossip.rb
class TagGossip < ApplicationRecord
    belongs_to :gossip 
    belongs_to :tag 
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :city, required: false
    has_many :gossips
    has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def gossip
      @all_gossips= Gossip.all
      puts "*" * 50
      puts @all_gossips
      puts "*" * 50
    end
  
    def show_gossip
      @gossip = Gossip.find(:id)
    end
  end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def team
    end
  
    def contact
    end
  end

app/controllers/user_controller.rb
class UserController < ApplicationController
    def show
      @user = User.find(params[:user_id])
    end
  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def first_name
      puts "*" * 50
      puts params[:first_name]
      puts "*" * 50
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/gossip.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">WELCOME <span class="badge badge-secondary"><%= params[:first_name] %>! </span></h1>
    <p class="lead">Ici on aime raconter la vie des autres</p>
  </div>
</div>

<div class="col-sm text-center card-columns ">
            <% Gossip.all.each do |gossip| %>
            <div class="card shadow p-3 mb-5 bg-white" style="width: 18rem;">
              <div class="card-body">
                  <h5 class="card-title"><%= gossip.title %></h5>
                  <p class="card-text">Ecrit par <%= gossip.user.first_name%> <%= gossip.user.last_name%> </p>
                  <a href="../gossip/<%= gossip.id %>" class="btn btn-primary">Tu veux en savoir plus sur ce gossip?</a>
              </div>
            </div>
        <% end %>
    </div>

app/views/home/show_gossip.html.erb
<h1>Home#show_gossip</h1>
<p>Find me in app/views/home/show_gossip.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/sketchy/bootstrap.min.css" rel="stylesheet" integrity="sha384-N8DsABZCqc1XWbg/bAlIDk7AS/yNzT5fcKzg/TwfmTuUqZhGquVmpb5VvfmLcMzp" crossorigin="anonymous">
  <body>

    <nav class="navbar sticky-top navbar-expand-lg navbar-light" style="background-color: #eb4d5c">
    <h1 class="navbar-brand" href="#">Gossip</h1>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to "Home", home_gossip_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to "Team", team_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", contact_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </nav>

    <%= yield %>
    
  </body>
</html>

app/views/user/show.html.erb
<h2>Profil utilisateur</h2>

  <p> 
  Son prénom et nom : <%= @user.first_name %> <%= @user.last_name %><br/>
  Son mail : <%= @user.email %><br/>
  Son age : <%= @user.age %><br/>
  Sa ville : <%= @user.city.name %><br/>
  Ma vie, mon oeuvre: <%= @user.description %>
  </p>

app/views/welcome/first_name.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">BIENVENUE <%= params[:first_name] %>! </h1>
    <p class="lead">Ici c'est notre super site de potins, il est chouette, non ?</p>
  </div>
</div>